import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { openSans } from "@/fonts/fonts";
import { Suspense } from "react";
import Loading from "@/components/Others/Loading";
import { Toaster } from "sonner";
import StoreProvider from "./StoreProvider";
import { FormProvider } from "@/components/employer-account/FormContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
import GoogleTranslateProvider from "@/components/context/GoogleLang";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "And_Scheer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        data-new-gr-c-s-check-loaded="14.1244.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
        className="relative! z-20 top-0!"
      >
        <StoreProvider>
          <GoogleOAuthProvider clientId="959795390198-ijbhg4ob84kgulhod8iauk56iu9s779h.apps.googleusercontent.com">
            <GoogleTranslateProvider>
              <FormProvider>
                <Toaster position="top-center" expand={true} richColors />
                <Suspense fallback={<Loading />}>{children}</Suspense>
                {/* <Suspense>{children}</Suspense> */}
              </FormProvider>
            </GoogleTranslateProvider>
          </GoogleOAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
